version: "3.8"
services:
  app: # name of app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    container_name: file_sharing_app_container
  celery:
    restart: always
    build: .
    command: celery -A src.settings.celery worker --pool=solo -l info
    volumes:
      - .:/src/app
    depends_on:
      - redis
      - app
  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: celery -A src.settings beat -l info
    volumes:
      - .:/apps
    depends_on:
      - celery
      - redis
      - app
  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=file_sharing_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  pgdata: