version: "3.8"
services:
  app: # name of app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    container_name: file_sharing_app_container
  celery:
    restart: always
    build: .
    command: celery -A src.settings.celery worker --pool=solo -l info
    volumes:
      - .:/src/app
    depends_on:
      - redis
      - app
  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: celery -A src.settings beat -l info
    volumes:
      - .:/apps
    depends_on:
      - celery
      - redis
      - app
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  pgdata: