# Generated by Django 3.2 on 2022-05-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='code',
            field=models.CharField(default='8962', max_length=128),
        ),
    ]
