# Generated by Django 3.2 on 2022-06-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filemodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='code',
        ),
    ]
