# Generated by Django 3.2 on 2022-06-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_filemodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
